#ifndef RESOURCE_GLOBAL_H
#define RESOURCE_GLOBAL_H

#include <QtGlobal>

#if defined(MEDIASTUDIO_RESOURCE_LIBRARY)
#  define MEDIASTUDIO_RESOURCE_EXPORT   Q_DECL_EXPORT
#else
#  define MEDIASTUDIO_RESOURCE_EXPORT   Q_DECL_IMPORT
#endif


#endif // RESOURCE_GLOBAL_H
